move VS initialisation after TYPE validation
group together initialisations for each types

diff --git a/apothecary/apothecary b/apothecary/apothecary
--- a/apothecary/apothecary
+++ b/apothecary/apothecary
@@ -326,67 +326,6 @@ while getopts t:a:b:d:s:j:hgvxfp opt ; do
 done
 shift $(( $OPTIND - 1))
 
-# used when building for vs - set to 15 if not set explicitly
-if [ "$TYPE" = "vs" ]; then
-    if [ -z ${VS_VER+x} ]; then
-	    echo "VS_VER was not set - setting to 15"
-	    VS_VER=15
-    else
-	    echo "VS_VER is set to '$VS_VER'"
-    fi
-
-    VS_64_BIT_ENV='VC\vcvarsall'
-
-    if [ -z ${PLATFORM+x}]; then
-        if [ $ARCH == 32 ]; then
-            PLATFORM=x86
-        elif [ $ARCH == 64 ]; then
-            PLATFORM=x64
-        fi
-
-        echo "PLATFORM set to '$PLATFORM', ${PLATFORM}_${VS_VER}"
-    fi
-
-    if [ -z ${VS_BIN_PATH+x} ]; then
-        if [ "${PLATFORM}_${VS_VER}" = "x86_14" ]; then
-            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN"
-        elif [ "${PLATFORM}_${VS_VER}" = "x64_14" ]; then
-            VS_BIN_PATH="/c/Program Files (x86)/MSBuild/14.0/bin/amd64:/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64"
-        elif [ "${PLATFORM}_${VS_VER}" = "x86_15" ]; then
-			VS_VER_DIR=$(ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/" | tail -1)
-            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/$VS_VER_DIR/bin/HostX86/x86"
-        elif [ "${PLATFORM}_${VS_VER}" = "x64_15" ]; then
-			VS_VER_DIR=$(ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/" | tail -1)
-            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/$VS_VER_DIR/bin/HostX64/x64"
-        fi
-
-		export PATH=$VS_BIN_PATH:$PATH
-
-        (
-        	# with parentheses we open a new sub-shell scope to make sure we're not overwriting any presets for IFS
-	        # set input field separator to colon (:) for current scope
-	        IFS=:
-	        for vs_bin_directory in ${VS_BIN_PATH}; do
-	        	# we must make sure each given directory exists
-	 	        if [ ! -d ${vs_bin_directory} ]; then
-	    	        echo "Couldn't confirm Visual Studio path exists: '$vs_bin_directory', probably installed on a non standard location?"
-	        	    exit 1
-	        	else
-	        		echo "Confirmed VS_BIN_PATH element exists: '${vs_bin_directory}'"
-		        fi
-
-	        done
-        )
-
-        echo "VS_BIN_PATH was not set - setting to $VS_BIN_PATH"
-
-        # Test for existence of directory where cmake should live
-        # then prepend cmake path to PATH
-        if [ -d "/c/Program Files/CMake/bin/" ]; then
-            export PATH="/c/Program Files/CMake/bin/:$PATH"
-        fi
-    fi
-fi
 
 # get command
 if [ $# -gt 0 ] ; then
@@ -1289,6 +1228,68 @@ if [ "$TYPE" == "linuxarmv6l" ] || [ "$TYPE" == "linuxarmv7l" ]; then
             echoWarning Trying to cross compile but TOOLCHAIN_ROOT not set
             echoWarning Trying to continue in case PATH is set to correct toolchain
             echoWarning If compiling fails try setting TOOLCHAIN_ROOT to root of cross compiler toolchain
+        fi
+    fi
+fi
+
+# used when building for vs - set to 15 if not set explicitly
+if [ "$TYPE" = "vs" ]; then
+    if [ -z ${VS_VER+x} ]; then
+	    echo "VS_VER was not set - setting to 15"
+	    VS_VER=15
+    else
+	    echo "VS_VER is set to '$VS_VER'"
+    fi
+
+    VS_64_BIT_ENV='VC\vcvarsall'
+
+    if [ -z ${PLATFORM+x}]; then
+        if [ $ARCH == 32 ]; then
+            PLATFORM=x86
+        elif [ $ARCH == 64 ]; then
+            PLATFORM=x64
+        fi
+
+        echo "PLATFORM set to '$PLATFORM', ${PLATFORM}_${VS_VER}"
+    fi
+
+    if [ -z ${VS_BIN_PATH+x} ]; then
+        if [ "${PLATFORM}_${VS_VER}" = "x86_14" ]; then
+            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN"
+        elif [ "${PLATFORM}_${VS_VER}" = "x64_14" ]; then
+            VS_BIN_PATH="/c/Program Files (x86)/MSBuild/14.0/bin/amd64:/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64"
+        elif [ "${PLATFORM}_${VS_VER}" = "x86_15" ]; then
+			VS_VER_DIR=$(ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/" | tail -1)
+            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/$VS_VER_DIR/bin/HostX86/x86"
+        elif [ "${PLATFORM}_${VS_VER}" = "x64_15" ]; then
+			VS_VER_DIR=$(ls "/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/" | tail -1)
+            VS_BIN_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/$VS_VER_DIR/bin/HostX64/x64"
+        fi
+
+		export PATH=$VS_BIN_PATH:$PATH
+
+        (
+        	# with parentheses we open a new sub-shell scope to make sure we're not overwriting any presets for IFS
+	        # set input field separator to colon (:) for current scope
+	        IFS=:
+	        for vs_bin_directory in ${VS_BIN_PATH}; do
+	        	# we must make sure each given directory exists
+	 	        if [ ! -d ${vs_bin_directory} ]; then
+	    	        echo "Couldn't confirm Visual Studio path exists: '$vs_bin_directory', probably installed on a non standard location?"
+	        	    exit 1
+	        	else
+	        		echo "Confirmed VS_BIN_PATH element exists: '${vs_bin_directory}'"
+		        fi
+
+	        done
+        )
+
+        echo "VS_BIN_PATH was not set - setting to $VS_BIN_PATH"
+
+        # Test for existence of directory where cmake should live
+        # then prepend cmake path to PATH
+        if [ -d "/c/Program Files/CMake/bin/" ]; then
+            export PATH="/c/Program Files/CMake/bin/:$PATH"
         fi
     fi
 fi
